#!/bin/bash

ROOT=/opt/omniscient
EXTENSIONS="*.doc *.docx *.html *.odt *.pdf *.xls *.xlsx *.ods *.ppt *.pptx *.txt"

 find ~/ -name '*.mp3' -exec mv -t $ROOT/Music {} +
 find ~/ -name '*.pdf' -exec mv -t $ROOT/Documents {} +
 find ~/ -name '*.txt' -exec mv -t $ROOT/Documents {} +
 find ~/ -name '*.html' -exec mv -t $ROOT/web {} +
 find ~/ -name '*.odt' -exec mv -t $ROOT/Documents {} +
 find ~/ -name '*.docx' -exec mv -t $ROOT/Documents {} +
 find ~/ -name '*.ods' -exec mv -t $ROOT/Documents {} +
