#!/bin/bash

sudo cp /usr/local/bin/asound.state /var/lib/alsa/asound.state
sudo alsa force-reload
alsactl init
sudo alsactl store --file /var/lib/alsa/asound.state
sudo alsa force-reload

sudo reboot
