#!/bin/bash

echo
echo "		RMTRASH - PURGE AND BLOWOFF ALL FREE SPACE		"
echo 

echo "    Removing:    sudo rm -rf ~/.local/share/Trash/  ~/.cache/thumbnails/*  /var/cache/apt/*  /var/cache/apt/archives/*  /var/lib/apt/lists/*  /var/lib/snapd/snaps/partial/*  /home/$USER/.cache/*   "
echo | sleep 2
sudo rm -rf ~/.local/share/Trash/
sudo rm -rf ~/.cache/thumbnails/*
sudo rm -rf /var/cache/apt/*
sudo rm -rf /var/cache/apt/archives/*
sudo rm -rf /var/lib/apt/lists/*
sudo rm -rf /var/lib/snapd/snaps/partial/*
sudo rm -rf /home/$USER/.cache/*
echo
echo "WARNING REMOVING ALL LOGS!" | sleep 2
echo
sudo find /var/log -type f -delete
echo
sudo apt-get autoremove --purge

#Check the Drive Space Used by Cached Files
#du -sh /var/cache/apt/archives

#Clean all the log file
#for logs in `find /var/log -type f`;  do > $logs; done


echo "Find Logs..." | sleep 2
logs=`find /var/log -type f`
for i in $logs
do
> $i
done

#Getting rid of partial packages
echo "Getting Rid Of Partial Packages..." | sudo apt-get clean && apt-get autoclean && sudo apt-get remove --purge -y software-properties-common

#Getting rid of no longer required packages
sudo apt-get autoremove -y


#Getting rid of orphaned packages
echo "Getting Rid Of All Orphaned Packages With Deborphan Temporary Install..."
sudo apt install deborphan && sudo deborphan | xargs sudo apt-get -y remove --purge && sudo apt remove -y deborphan

#Free up space by clean out the cached packages
#apt-get clean

# Remove the Trash
echo "Remove All Trash..."
#rm -rf /home/$USER/.local/share/Trash/*/**
sudo rm -rf /root/.local/share/Trash/*/**

# Remove Man

#rm -rf /usr/share/man/?? 
#rm -rf /usr/share/man/??_*

#Delete all .gz and rotated file
echo "Find And Delete All Rotated Logs..."
sudo find /var/log -type f -regex ".*\.gz$" | xargs rm -Rf
sudo find /var/log -type f -regex ".*\.[0-9]$" | xargs rm -Rf

#Cleaning the old kernels
echo "Clean Old Kernels..."
dpkg-query -l|grep linux-im*
#dpkg-query -l |grep linux-im*|awk '{print $2}'
sudo apt-get purge $(dpkg -l 'linux-*' | sed '/^ii/!d;/'"$(uname -r | sed "s/\(.*\)-\([^0-9]\+\)/\1/")"'/d;s/^[^ ]* [^ ]* \([^ ]*\).*/\1/;/[0-9]/!d' | head -n -1) --assume-yes
sudo apt-get install linux-headers-`uname -r|cut -d'-' -f3`-`uname -r|cut -d'-' -f4`

echo "Autoremove Old File Configs..." | sudo apt autoremove

#Cleaning is completed
echo "Cleaning Complete..."  && echo "Running Bleachbit..." | sudo bleachbit
