#!/bin/bash

# Define variables
MODULES="https://blackarch.org/forensic.html"
TESTDISK="/media/jeremy/backup/TESTDISK"
REGEX=""
PII="accountNumber custName custID cardHolder card Phone Address SSN creditcard"
DI="https://www.linuxtopic.com/2021/05/Regular%20Expression%20-%20How%20to%20Remove%20PII%20Data%20from%20File%20%20How%20to%20Masked%20Personal%20Information%20from%20Json%20Logs.html"
rezipdirs=""
dirs=""
filexe="filexe"

# Move files with specified extensions
move_files() {
    mkdir "$1"
    mv "*.$1" "$1"
}

# Clean up empty directories and files
cleanup_empty() {
    find . -depth -mindepth 1 -type d -empty -exec rmdir {} \; -o -type f -empty -exec rm -f {} \;
}

# Main loop
main_loop() {
    while read -r line; do
        echo "$line" | grep -E "$REGEX" && continue
        
        # Process file extensions
        ext="${line##*.}"
        mkdir -p "$ext"
        mv "$line" "$ext"

        # Add extension to rezipdirs
        rezipdirs="$rezipdirs $ext"
    done
}

# Entry point
echo "TESTDISK WORKFLOW"

cd "$TESTDISK"

tree -L 2 -f "$TESTDISK"
tree -R -L 2 -f --prune "$TESTDISK" -o "$TESTDISK/tree_report.log"

find . -maxdepth 2 -type f -exec mv {} .. \;

sudo find recup* -depth -mindepth 2 -type d -empty -exec rmdir {} \; ls -d && echo "ZERO DIRS LEFT!"

main_loop

# Move files to directories based on extensions
move_files "SH"
move_files "PY"
# ... add more move_files calls for other extensions

# Create LOOT directory and move files into it
mkdir -p "$TESTDISK/LOOT"
mv EXE JPG PNG PDF TXT AVI XZ AVI 7ZIP CSV DB DEB DISKIMG DOC DOCX GZ ISO MP3 MP4 RAR TAR MOV WMV OGG REG -t "$TESTDISK/LOOT"
zip -ur "$TESTDISK/LOOT.zip" "$TESTDISK/LOOT"

cleanup_empty

# Perform additional actions like zgrep, binwalk, etc.
zgrep -c "linux" "$TESTDISK/*.gz"
# ... add more commands for other tasks

# Truncate empty dirs and files
cleanup_empty
