#!/bin/bash

echo " YTDL - BATCH HARVEST YOUTUBE MP3 TO STUDIO QUALITY "
while true; do 
echo
echo -n "Enter Youtube Playlist: "
read http
python3 /usr/local/bin/youtube-dl -o "%(title)s.%(ext)s" $http;
done
#echo "Converting To MP3 Studio Quality 320kb Lossless" | for f in *.mp3;do ffmpeg -i "${f}" -ab 320k -map_metadata 0 -id3v2_ve>
#youtube-dl --recode-video mp4 https://www.youtube.com/watch?v=yVpbFMhOAwE

